.PHONY: build test lint fmt

build:
	cmake -S . -B build && cmake --build build

test:
	cmake -S . -B build && cmake --build build

lint:
	cmake -S . -B build

fmt:
	@echo "No C++ formatter configured"
